# Data Wrangling.

In [1]:
# loading modules
from IPython.display import display, HTML
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [15]:
personality = pd.read_csv('personality_scores.csv', sep=';')

In [16]:
#checking for duplicates in the data set.
duplicates = personality[personality.duplicated(['ID'])]
print('The duplicate data in this data are:', duplicates, sep='\n')

The duplicate data in this data are:
Empty DataFrame
Columns: [ID, Section 5 of 6 [I am always prepared.], Section 5 of 6 [I am easily disturbed.], Section 5 of 6 [I am exacting (demanding) in my work.], Section 5 of 6 [I am full of ideas.], Section 5 of 6 [I am interested in people.], Section 5 of 6 [I am not interested in abstract ideas.], Section 5 of 6 [I am not interested in other people's problems.], Section 5 of 6 [I am not really interested in others.], Section 5 of 6 [I am quick to understand things.], Section 5 of 6 [I am quiet around strangers.], Section 5 of 6 [I am relaxed most of the time.], Section 5 of 6 [I am the life of the party.], Section 5 of 6 [I change my mood a lot.], Section 5 of 6 [I do not have a good imagination.], Section 5 of 6 [I don't like to draw attention to myself.], Section 5 of 6 [I don't mind being the center of attention.], Section 5 of 6 [I don't talk a lot.], Section 5 of 6 [I feel comfortable around people.], Section 5 of 6 [I feel little concern for others.], Section 5 of 6 [I feel others' emotions.], Section 5 of 6 [I follow a schedule.], Section 5 of 6 [I get chores done right away.], Section 5 of 6 [I get irritated easily.], Section 5 of 6 [I get stressed out easily.], Section 5 of 6 [I get upset easily.], Section 5 of 6 [I have a rich vocabulary.], Section 5 of 6 [I have a soft (kind) heart.], Section 5 of 6 [I have a vivid imagination.], Section 5 of 6 [I have difficulty understanding abstract ideas.], Section 5 of 6 [I have excellent ideas.], Section 5 of 6 [I have frequent mood swings.], Section 5 of 6 [I have little to say.], Section 5 of 6 [I insult people.], Section 5 of 6 [I keep in the background.], Section 5 of 6 [I leave my belongings lying around.], Section 5 of 6 [I like order.], Section 5 of 6 [I make a mess of things.], Section 5 of 6 [I make people feel at ease.], Section 5 of 6 [I neglect my duties.], Section 5 of 6 [I often feel blue (down).], Section 5 of 6 [I often forget to put things back in their proper place], Section 5 of 6 [I pay attention to details.], Section 5 of 6 [I seldom feel blue (down).], Section 5 of 6 [I spend time reflecting on things.], Section 5 of 6 [I start conversations.], Section 5 of 6 [I sympathize with others' feelings.], Section 5 of 6 [I take time out for others.], Section 5 of 6 [I talk to a lot of different people at parties.], Section 5 of 6 [I use difficult words.], Section 5 of 6 [I worry about things.], Unnamed: 51, Unnamed: 52, Unnamed: 53, Unnamed: 54, Unnamed: 55, Unnamed: 56, Unnamed: 57, Unnamed: 58, Unnamed: 59, Unnamed: 60, Unnamed: 61, Unnamed: 62, Unnamed: 63, Unnamed: 64, Unnamed: 65, Unnamed: 66, Unnamed: 67, Unnamed: 68, IPIP_HIGH_RISK]
Index: []

[0 rows x 70 columns]

In [17]:
#checking for duplicates in the data set.
personality.drop_duplicates(subset=['ID'], inplace=True)

# Assert Statement for modification.
personality['ID'].unique().sum() == personality['ID'].sum()

True

In [18]:
personality.head()

,ID,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,IPIP_HIGH_RISK
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
#creating new columns
personality = pd.concat([personality, pd.DataFrame(columns = ['conscientiousness', 'emotional stability', 'openness to new experience', 'agreeableness', 'extraversion'])],sort=True)

personality

,ID,IPIP_HIGH_RISK,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],...,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,agreeableness,conscientiousness,emotional stability,extraversion,openness to new experience
0,0.0,NaN,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,NaN,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.0,NaN,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3.0,NaN,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.0,NaN,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1550,1550.0,NaN,"(3, 5)","(4, 5)","(3, 1)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1551,1551.0,NaN,"(3, 3)","(4, 5)","(3, 5)","(5, 3)","(2, 5)","(5, 3)","(2, 3)","(2, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1552,1552.0,NaN,"(3, 5)","(4, 3)","(3, 5)","(5, 5)","(2, 5)","(5, 5)","(2, 3)","(2, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1553,1553.0,NaN,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1554,1554.0,NaN,"(3, 3)","(4, 5)","(3, 1)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
def sum_subscales(personality, row, number):
    
    count = 0
    for column in personality:
        checks = row[column]
        if row.column[1] == number:
            number = checks[1]
            num = checks[4]
            if number == number:
                count += num
    return count

personality['Extraversion'] = personality.apply(lambda row: sum_subscales(row,'1', personality), axis = 1)
personality

TypeError: ('string indices must be integers', 'occurred at index 0')

In [19]:
departments = pd.read_csv('departments.csv', sep=';')
pers_by_dept = pd.merge(personality, departments).set_index('ID')

In [20]:
pers_by_dept

,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],Section 5 of 6 [I am quiet around strangers.],...,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,IPIP_HIGH_RISK,Department
ID,,,,,,,,,,,,,,,,,,,,,
0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)","(1, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data
1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)","(1, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data
2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)","(1, 1)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data
3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)","(1, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data
4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)","(1, 1)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1550,"(3, 5)","(4, 5)","(3, 1)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)","(1, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Web dev
1551,"(3, 3)","(4, 5)","(3, 5)","(5, 3)","(2, 5)","(5, 3)","(2, 3)","(2, 5)","(5, 5)","(1, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Web dev
1552,"(3, 5)","(4, 3)","(3, 5)","(5, 5)","(2, 5)","(5, 5)","(2, 3)","(2, 3)","(5, 5)","(1, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Web dev
1553,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)","(1, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Web dev
1554,"(3, 3)","(4, 5)","(3, 1)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 5)","(5, 3)","(1, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Web dev

In [26]:
# Assert Statement for modification.
len(pers_by_dept) == len(departments)

True